services:
  nicedentist-manager-api:
    build:
      context: .
      dockerfile: src/NiceDentist.Manager.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=NiceDentistManagerDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=true;
      - DatabaseProvider=SqlServer
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=nicedentist
      - RabbitMQ__Password=Your_rabbit_password123!
      - AuthService__BaseUrl=http://authapi:8080
    ports:
      - "5001:8081"
    restart: unless-stopped
    networks:
      - nicedentist-network
      - default

networks:
  nicedentist-network:
    external: true
