@NiceDentist.Manager.Api_HostAddress = http://localhost:5210

# NiceDentist Manager API endpoints will be added here
# Example:
# GET {{NiceDentist.Manager.Api_HostAddress}}/api/customers
# Accept: application/json

###
